# Generated by Django 3.1.5 on 2021-02-06 22:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
