# Generated by Django 3.1.5 on 2021-02-07 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210207_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
